package com.reportssent.plugins.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.reportssent.plugins.model.Element;
import com.reportssent.plugins.service.ElementLocalServiceUtil;

/**
 * The extended model base implementation for the Element service. Represents a row in the &quot;OH_Element&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ElementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ElementImpl
 * @see com.reportssent.plugins.model.Element
 * @generated
 */
public abstract class ElementBaseImpl extends ElementModelImpl
    implements Element {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a element model instance should use the {@link Element} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ElementLocalServiceUtil.addElement(this);
        } else {
            ElementLocalServiceUtil.updateElement(this);
        }
    }
}
