package com.reportssent.plugins.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.reportssent.plugins.model.Reports;
import com.reportssent.plugins.service.ReportsLocalServiceUtil;

/**
 * The extended model base implementation for the Reports service. Represents a row in the &quot;OH_Reports&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReportsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReportsImpl
 * @see com.reportssent.plugins.model.Reports
 * @generated
 */
public abstract class ReportsBaseImpl extends ReportsModelImpl
    implements Reports {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a reports model instance should use the {@link Reports} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ReportsLocalServiceUtil.addReports(this);
        } else {
            ReportsLocalServiceUtil.updateReports(this);
        }
    }
}
