package com.statuspatients.plugins.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.statuspatients.plugins.model.Patients;
import com.statuspatients.plugins.service.PatientsLocalServiceUtil;

/**
 * The extended model base implementation for the Patients service. Represents a row in the &quot;OH_Patients&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatientsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PatientsImpl
 * @see com.statuspatients.plugins.model.Patients
 * @generated
 */
public abstract class PatientsBaseImpl extends PatientsModelImpl
    implements Patients {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a patients model instance should use the {@link Patients} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PatientsLocalServiceUtil.addPatients(this);
        } else {
            PatientsLocalServiceUtil.updatePatients(this);
        }
    }
}
